config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'news#index'
  resources :news
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/news.rb
class News < ActiveRecord::Base
    validates :title, presence: true, length: {minimum: 3, maximum: 50}
    validates :description, presence: true, length: {minimum: 18, maximum: 300}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
    def index
        @news = News.all
    end
    def new
        @news = News.new
    end
    def edit
        @news = News.find(params[:id])
    end
    
    def update
        @news = News.find(params[:id])
        if @news.update(news_params)
            flash[:notice] = "News Has Been Updated Succesfully"
            redirect_to news_path(@news)
        else
            render 'edit'
        end
    end
    def create
        @news = News.new(news_params)
        if @news.save
            flash[:notice] = "News Has Been Created Succesfully"
            redirect_to news_path(@news)
        else
            render 'new'
        end
    end

    def show 
        @news = News.find(params[:id])
    end

    def destroy
        @news = News.find(params[:id])
        @news.destroy
        flash[:notice] = "News Has Been Deleted Succesfully"
        redirect_to action: "index"
    end
    private
        def news_params
            params.require(:news).permit(:title, :description)
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <ul>
      <li><%= msg %></li>
    </ul>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TikvahNews</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'bootstrap.min', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'magnific-popup', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'jquery-ui', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'owl.carousel.min', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'owl.theme.default.min', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'bootstrap-datepicker', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'aos', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'style', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="site-wrap">

  <div class="site-mobile-menu">
    <div class="site-mobile-menu-header">
      <div class="site-mobile-menu-close mt-3">
        <span class="icon-close2 js-menu-toggle"></span>
      </div>
    </div>
    <div class="site-mobile-menu-body"></div>
  </div>
  
  <header class="site-navbar" role="banner">
    <div class="container-fluid">
      <div class="row align-items-center">
        
        <div class="col-12 search-form-wrap js-search-form">
          <form method="get" action="#">
            <input type="text" id="s" class="form-control" placeholder="Search...">
            <button class="search-btn" type="submit"><span class="icon-search"></span></button>
          </form>
        </div>

        <div class="col-4 site-logo">
          <a href="index.html" class="text-black h2 mb-0">TIKVAH NEWS</a>
        </div>

        <div class="col-8 text-right">
          <nav class="site-navigation" role="navigation">
            <ul class="site-menu js-clone-nav mr-auto d-none d-lg-block mb-0">
              <li><%= link_to 'Home', root_path %></li>
              <li><%= link_to 'Add News', new_news_path %></li>
              <li><%= link_to 'About', root_path %></li>
              <li class="d-none d-lg-inline-block"><a href="#" class="js-search-toggle"><span class="icon-search"></span></a></li>
            </ul>
          </nav>
          <a href="#" class="site-menu-toggle js-menu-toggle text-black d-inline-block d-lg-none"><span class="icon-menu h3"></span></a></div>
        </div>

    </div>
  </header>

  <%= render 'layouts/messages' %>
  <%= yield %>
  
  <div class="site-footer">
    <div class="container">
      <div class="row mb-5">
        <div class="col-md-4">
          <h3 class="footer-heading mb-4">About Us</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Placeat reprehenderit magnam deleniti quasi saepe, consequatur atque sequi delectus dolore veritatis obcaecati quae, repellat eveniet omnis, voluptatem in. Soluta, eligendi, architecto.</p>
        </div>
        <div class="col-md-3 ml-auto">
          
        </div>
        <div class="col-md-4">
          

          <div>
            <h3 class="footer-heading mb-4">Connect With Us</h3>
            <p>
              <a href="#"><span class="icon-facebook pt-2 pr-2 pb-2 pl-0"></span></a>
              <a href="#"><span class="icon-twitter p-2"></span></a>
              <a href="#"><span class="icon-instagram p-2"></span></a>
              <a href="#"><span class="icon-rss p-2"></span></a>
              <a href="#"><span class="icon-envelope p-2"></span></a>
            </p>
          </div>
        </div>
      </div>
      
    </div>
  </div>
  
</div>
  </body>
</html>

app/views/layouts/messages.hmtl.erb
<% flash.each do |name, msg| %>
    <ul>
      <li><%= msg %></li>
    </ul>
  <% end %>

app/views/news/_form.html.erb
<div class="site-section bg-light">
      <div class="container">
        <%= render 'shared/errors', obj:@news %>
        <div class="row">
            
          <div class="col-md-8 offset-md-2 mb-5">

            

            <%= form_for(@news, :html =>{class:"p-5 bg-white"}) do |f| %>

              <div class="row form-group">
                
                <div class="col-md-12">
                <%= f.label :title, class:"text-black" %><br/>
                <%= f.text_field :title, class:"form-control" %>
                  
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-12">
                <%= f.label :description, class:"text-black"  %><br/>
                <%= f.text_area :description, cols:"30", rows:"7", class:"form-control", placeholder:"Write your description here..."%>
                  
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-12">
                <%= f.submit class:"btn btn-primary py-2 px-4 text-white" %>
                </div>
              </div>

  
              <% end %>
          </div>
          
        </div>
      </div>
    </div>

app/views/news/edit.html.erb
<%= render 'form' %>

app/views/news/index.html.erb
<div class="site-section">
    <div class="container">
      <div class="row mb-5">
        <div class="col-12">
          <h2>Recent News</h2>
        </div>
      </div>
      <div class="row">
      <% @news.each do |n|%>
        <div class="col-lg-4 mb-4">
          <div class="entry2">
            <div class="excerpt">
            <span class="post-category text-white bg-secondary mb-3">Politics</span>

            <h2><%= link_to n.title, news_path(n) %></h2>
            <div class="post-meta align-items-center text-left clearfix">
              <span class="d-inline-block mt-1">By <a href="#">Carrol Atkinson</a></span>
              <span>&nbsp;-&nbsp; July 19, 2019</span>
            </div>
            
              <p><%= n.description %></p>
              <p><%= link_to 'Read More', news_path(n) %> | <%= link_to 'Edit', edit_news_path(n) %>  | <%= link_to 'Delete', news_path(n), method: :delete, data:{confirm:"Are you sure?"} %></p>
            </div>
          </div>
        </div>
        <% end %>
      </div>
      
    </div>
  </div>

app/views/news/new.html.erb
<%= render 'form' %>

app/views/news/show.html.erb
<div class="site-cover site-cover-sm same-height overlay single-page" style="background-image: url('images/img_2.jpg');">
      <div class="container">
        <div class="row same-height justify-content-center">
          <div class="col-md-12 col-lg-10">
            <div class="post-entry text-center">
              <span class="post-category text-white bg-success mb-3">Nature</span>
              <h1 class="mb-4"><%= @news.title %></h1>
              <div class="post-meta align-items-center text-center">
                <span class="d-inline-block mt-1">By Carrol Atkinson</span>
                <span>&nbsp;-&nbsp; February 10, 2019</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <section class="site-section py-lg">
    <div class="container">
      
      <div class="row blog-entries element-animate">

        <div class="col-md-12 col-lg-8 main-content">
          
          <div class="post-content-body">
            <p><%= @news.description %></p>
           </div>
        </div>
     </div>
    </div>
</section>

app/views/pages/home.html.erb
<h1>home page</h1>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
        <div class="row">
          <div class="col-md-6 bg-warning offset-md-3 mb-5">
            <p><%= pluralize(obj.errors.count,"error")%>
            prohibited thies news from being saved</p>
            <ul>
            <% obj.errors.full_messages.each do |msg| %>
                <li> <%= msg %> </li>
            <% end %>
        </ul>
          </div>
         
        </div>
        <% end %>